/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R365RouteImport } from './routes/365'
import { Route as FutureRouteImport } from './routes/future'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as LittleThingsRouteImport } from './routes/little-things'
import { Route as TwelveRouteImport } from './routes/twelve'
import { Route as UniverseRouteImport } from './routes/universe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R365Route = R365RouteImport.update({
  id: '/365',
  path: '/365',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const LittleThingsRoute = LittleThingsRouteImport.update({
  id: '/little-things',
  path: '/little-things',
  getParentRoute: () => rootRouteImport,
} as any)
const TwelveRoute = TwelveRouteImport.update({
  id: '/twelve',
  path: '/twelve',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/future': typeof FutureRoute
  '/letter': typeof LetterRoute
  '/little-things': typeof LittleThingsRoute
  '/twelve': typeof TwelveRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/future': typeof FutureRoute
  '/letter': typeof LetterRoute
  '/little-things': typeof LittleThingsRoute
  '/twelve': typeof TwelveRoute
  '/universe': typeof UniverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/365': typeof R365Route
  '/future': typeof FutureRoute
  '/letter': typeof LetterRoute
  '/little-things': typeof LittleThingsRoute
  '/twelve': typeof TwelveRoute
  '/universe': typeof UniverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/365'
    | '/future'
    | '/letter'
    | '/little-things'
    | '/twelve'
    | '/universe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/365'
    | '/future'
    | '/letter'
    | '/little-things'
    | '/twelve'
    | '/universe'
  id:
    | '__root__'
    | '/'
    | '/365'
    | '/future'
    | '/letter'
    | '/little-things'
    | '/twelve'
    | '/universe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R365Route: typeof R365Route
  FutureRoute: typeof FutureRoute
  LetterRoute: typeof LetterRoute
  LittleThingsRoute: typeof LittleThingsRoute
  TwelveRoute: typeof TwelveRoute
  UniverseRoute: typeof UniverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/365': {
      id: '/365'
      path: '/365'
      fullPath: '/365'
      preLoaderRoute: typeof R365RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/little-things': {
      id: '/little-things'
      path: '/little-things'
      fullPath: '/little-things'
      preLoaderRoute: typeof LittleThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twelve': {
      id: '/twelve'
      path: '/twelve'
      fullPath: '/twelve'
      preLoaderRoute: typeof TwelveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R365Route: R365Route,
  FutureRoute: FutureRoute,
  LetterRoute: LetterRoute,
  LittleThingsRoute: LittleThingsRoute,
  TwelveRoute: TwelveRoute,
  UniverseRoute: UniverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
